-- Classroom library v2 migration. Run in Supabase SQL Editor before merging the app.
-- Student catalog is an allowlisted, read-only RPC; never grant anonymous SELECT
-- on Students, Classes, Checkouts, Reservations, or the full Books table.
begin;
alter table public."Series" add column if not exists "Expected Books" integer;
alter table public."Books" add column if not exists "Reading Level" text;
create table if not exists public."Reservations" (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public."Books"(id) on delete cascade,
  student_id bigint not null references public."Students"(id) on delete cascade,
  created_at timestamptz not null default now(),
  status text not null default 'waiting' check (status in ('waiting','fulfilled','cancelled'))
);
create unique index if not exists reservations_one_waiting_per_student_book
  on public."Reservations"(book_id,student_id) where status='waiting';
create index if not exists reservations_queue on public."Reservations"(book_id,status,created_at,id);
alter table public."Reservations" enable row level security;
revoke all on public."Reservations" from anon;
grant select,insert,update,delete on public."Reservations" to authenticated;
grant usage,select on sequence public."Reservations_id_seq" to authenticated;
drop policy if exists reservations_teacher_read on public."Reservations";
drop policy if exists reservations_teacher_insert on public."Reservations";
drop policy if exists reservations_teacher_update on public."Reservations";
drop policy if exists reservations_teacher_delete on public."Reservations";
-- Only authenticated teachers may operate reservations. If other authenticated
-- accounts exist, replace auth.role() with a teacher allowlist before enabling.
create policy reservations_teacher_read on public."Reservations" for select to authenticated using (auth.uid() is not null);
create policy reservations_teacher_insert on public."Reservations" for insert to authenticated with check (auth.uid() is not null);
create policy reservations_teacher_update on public."Reservations" for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);
create policy reservations_teacher_delete on public."Reservations" for delete to authenticated using (auth.uid() is not null);

-- No private rows/identifiers from students or checkouts are returned.
create or replace function public.student_catalog()
returns jsonb
language sql stable security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', b.id,
    'title', b."Title",
    'author', b."Author",
    'description', b."Description",
    'cover', b."Cover URL",
    'genre', b."Genre",
    'genres', b."Genres",
    'series', b."Series",
    'series_number', b."Series #",
    'reading_level', b."Reading Level",
    'available', greatest(0,coalesce(b."Copies",0) - coalesce(used.n,0))
  ) order by b."Title"), '[]'::jsonb)
  from public."Books" b
  left join lateral (
    select count(*)::integer n from public."Checkouts" c
    where c.book_id=b.id and c."Return Date" is null
  ) used on true;
$$;
revoke all on function public.student_catalog() from public;
grant execute on function public.student_catalog() to anon,authenticated;
commit;
