-- Run once in the Supabase SQL Editor before using the Quick Reads page.
-- Classroom selections are independent of formal checkouts.
create table if not exists public."QuickReads" (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public."Books"(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  recorded_by uuid not null default auth.uid()
);
create index if not exists quick_reads_book_idx on public."QuickReads"(book_id);
create index if not exists quick_reads_date_idx on public."QuickReads"(recorded_at desc);
alter table public."QuickReads" enable row level security;
drop policy if exists "Quick Reads teacher select" on public."QuickReads";
drop policy if exists "Quick Reads teacher insert" on public."QuickReads";
drop policy if exists "Quick Reads teacher delete" on public."QuickReads";
create policy "Quick Reads teacher select" on public."QuickReads" for select to authenticated using (true);
create policy "Quick Reads teacher insert" on public."QuickReads" for insert to authenticated with check (recorded_by = auth.uid());
create policy "Quick Reads teacher delete" on public."QuickReads" for delete to authenticated using (recorded_by = auth.uid());
